<a href="https://colab.research.google.com/github/bjungweapon/mjc.ai.ml/blob/102_HOMEWORK/basic_np_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
ar1 = np.array([1,2,3,4,5])
ar2 = np.array([[1,2,3],[4,5,6]])

In [ ]:
print (ar1)

[1 2 3 4 5]


In [ ]:
print (ar2)

[[1 2 3]
 [4 5 6]]


In [ ]:
x = np.array( range(8))
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
x.reshape(4,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])