<a href="https://colab.research.google.com/github/bjungweapon/mjc.ai.ml/blob/ANDREIS/np.coo_ex1-1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import pandas as pd
import numpy as np


from scipy import sparse

#대각선 원소는 1이고 나머지는 0인 2차원 배열을 만든다.

In [10]:
eye = np.eye(4)
print ("Numpy 배열 = \n", eye)

Numpy 배열 = 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [15]:
data = np.ones(4)

raw_indices = np.arange(4)
col_indices = np.arange(4)

eye_coo = sparse.coo_matrix((data, ( raw_indices, col_indices)))

print("COO 표현:\n", eye_coo)

COO 표현:
 <COOrdinate sparse matrix of dtype 'float64'
	with 4 stored elements and shape (4, 4)>
  Coords	Values
  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0
